"""Constants for the Windhager Heater integration."""

CLIMATE_FUNCTION_TYPE = 14
DEFAULT_USERNAME = "USER"
DOMAIN = "windhager"
HEATER_FUNCTION_TYPE = 9
LOGWIN_FUNCTION_TYPE = 10
AEROWIN_FUNCTION_TYPE = 7
HYBRID_FUNCTION_TYPE = 26
UPDATE_INTERVAL = 60
